apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-webflux-demo-deployment-02
  labels:
    app: spring-webflux-demo-02
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-webflux-demoo-02
  template:
    metadata:
      labels:
        app: spring-webflux-demoo-02
    spec:
      containers:
        - name: spring-webflux-demo-container
          image: spring-webflux-demo:0.6
          imagePullPolicy: Never # local registry 사용
          ports:
            - containerPort: 80 # 서버 프로그램에 접속하기 위한 포트 번호
---
apiVersion: v1
kind: Service
metadata:
  name: spring-webflux-demo-serviceo-02
  labels:
    app: spring-webflux-demoo-02
spec:
  type: NodePort
  selector:
    app: spring-webflux-demoo-02
  ports:
    - nodePort: 30081 # node Port, 외부에서 접근
      port: 10080 # service port
      targetPort: 80 # pod port
      protocol: TCP
